(ns tram.logging
  "Convenience ns for reexporting `taoensso.telemere`"
  (:require [potemkin :refer [import-vars]]
            [taoensso.telemere :as t]))

(import-vars
  [taoensso.telemere
   *uid-fn*
   uncaught->error!
   get-filters
   signal!
   newline
   get-env
   get-min-levels
   with-handler+
   get-handlers
   msg-skip
   help:signal-creators
   event!?
   *xfn*
   handler:console
   with-xfn+
   pr-signal-fn
   comp-xfn
   with-ctx+
   clean-signal-fn
   set-ns-filter!
   with-min-level
   update-var-root!
   set-var-root!
   help:handlers
   log!
   trace!
   with-kind-filter
   level-aliases
   keep-callsite
   error-signal?
   msg-splice
   catch->error!
   with-out->telemere
   uncaught->handler!
   default-handler-dispatch-opts
   streams->telemere!
   error!
   with-id-filter
   set-min-level!
   spy!
   event!
   help:signal-options
   otel-default-providers_
   with-ns-filter
   otel-tracing?
   call-on-shutdown!
   handler:file
   stop-handlers!
   *ctx*
   with-signals
   signal-allowed?
   help:filters
   set-id-filter!
   log!?
   without-filters
   rate-limiter
   add-handler!
   dispatch-signal!
   with-signal
   *otel-tracer*
   with-handler
   remove-handler!
   set-ctx!
   format-signal-fn
   set-kind-filter!
   chance
   with-xfn
   set-xfn!
   help:handler-dispatch-options
   get-handlers-stats
   with-ctx
   with-err->telemere
   help:signal-content
   streams->reset!
   check-interop
   help:environmental-config
   with-streams->telemere])
