name: Unit Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  # Database configuration for CI - matches tram.edn test config
  POSTGRES_DB: tram_test
  PG_USER: runner
  PG_PASSWORD: tram
  TRAM_ENV: test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start PostgreSQL via docker compose
        env:
          USER: ${{ env.PG_USER }}
        run: |
          # Start the PostgreSQL container from root docker compose.yml
          # This uses the test database configuration from tram.edn
          docker compose up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          for i in {1..30}; do
            if docker exec tram-postgres-test pg_isready -U $PG_USER -d $POSTGRES_DB > /dev/null 2>&1; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting... ($i/30)"
            sleep 2
          done

          # Verify connection one more time
          docker exec tram-postgres-test pg_isready -U $PG_USER -d $POSTGRES_DB

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "23"

      - name: Cache Clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.cpcache
          key: ${{ runner.os }}-clojure-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clojure-

      - name: Install Clojure CLI tools
        run: |
          curl -O https://download.clojure.org/install/linux-install.sh
          chmod +x linux-install.sh
          sudo ./linux-install.sh

      - name: Run tests
        env:
          PGPASSWORD: ${{ env.PG_PASSWORD }}
        run: clojure -M:test

      - name: Install babashka
        run: |
          curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
          chmod +x install
          ./install

      - name: Run bb tests
        env:
          PGPASSWORD: ${{ env.PG_PASSWORD }}
        run: bin/test-bb
